receivers:
  # prometheusremotewrite:
  #  endpoint: "0.0.0.0:8888"  # 监听地址和端
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
    debug:
      verbosity: detailed
    jvmhttp:
      endpoint: http://127.0.0.1:4318
    simple:
#    otlphttp:
#      endpoint: http://127.0.0.1:4318
processors:
  jvmmetricr:


service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [jvmmetricr]
      exporters: [debug,jvmhttp,simple]
